#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_border                on
yabai -m config window_border_width          2
yabai -m config window_border_radius         0
yabai -m config active_window_border_color   0xFF5CCC96
yabai -m config normal_window_border_color   0xFFECF0C1
yabai -m config insert_feedback_color        0xFFFF4250
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  08
yabai -m config bottom_padding               08
yabai -m config left_padding                 08
yabai -m config right_padding                08
yabai -m config window_gap                   08

# ignore apps
yabai -m rule --add app=".*" manage=off
# yabai -m rule --add app="iTerm" manage=on
# yabai -m rule --add app="Sublime Text" manage=on
# yabai -m rule --add app="Google Chrome" manage=on

# Status bar (simple-bar)
yabai -m config external_bar all:28:0
