#!/usr/bin/env sh

# TODO: Create script that moves window to next available space, if none are available create one + autofocus to it
# TODO: Add IntelliJ to manage list, but fix all the child windows etc.

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_border                on
yabai -m config window_border_width          3
yabai -m config active_window_border_color   0xFFECF0C1
yabai -m config normal_window_border_color   0xFF555555
yabai -m config insert_feedback_color        0xFFFF4250
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  08
yabai -m config bottom_padding               08
yabai -m config left_padding                 08
yabai -m config right_padding                08
yabai -m config window_gap                   08

# ignore apps
yabai -m rule --add app="System Preferences" manage=off
yabai -m rule --add app="Mail" manage=off
yabai -m rule --add app="Calendar" manage=off
yabai -m rule --add app="Microsoft Teams" manage=off
yabai -m rule --add app="Microsoft Outlook" manage=off
yabai -m rule --add app="Finder" manage=off
yabai -m rule --add app="Slack" manage=off
yabai -m rule --add app="Discord" manage=off
yabai -m rule --add app="Docker Desktop" manage=off
yabai -m rule --add app="Installer" manage=off
yabai -m rule --add app="Pulse Secure" manage=off
yabai -m rule --add app="Preview" manage=off
yabai -m rule --add app="SQLDeveloper" manage=off
yabai -m rule --add app="MacPass" manage=off
yabai -m rule --add app="IntelliJ IDEA" manage=off
# yabai -m rule --add app=".*" manage=off

# Status bar (simple-bar)
yabai -m config external_bar all:28:0
